export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const { text } = req.body;
  if (!text) {
    return res.status(400).json({ error: 'No text provided' });
  }

  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    return res.status(500).json({ error: 'GEMINI_API_KEY is not configured in Vercel environment variables.' });
  }

  const prompt = `
You are an expert data extractor. I will provide you with the text extracted from an insurance proposal PDF. 
Your job is to extract the details and return them in a specific JSON format.
The text is from a proposal generated by our system, so it has standard sections like "Client Details", "Medical Insurance", "Term Life Insurance".

Extract the following information and return ONLY valid JSON matching this schema exactly:
{
  "proposerName": "string or empty",
  "clients": [
    { "name": "string", "dob": "YYYY-MM-DD", "tobacco": "Yes"|"No", "alcohol": "Yes"|"No", "ped": "Yes"|"No" }
  ],
  "medical": {
    "isPort": boolean,
    "portDate": "YYYY-MM-DD" or "",
    "basePolicies": [
      { "name": "string", "sum": "number (no commas)", "premium": "number (no commas)", "riders": "string" }
    ],
    "topupPolicies": [
      { "deductible": "number (no commas)", "sum": "number (no commas)", "premium": "number (no commas)" }
    ]
  },
  "term": {
    "groups": [
      {
        "insuredName": "string",
        "policies": [
           { "name": "string", "sum": "number (no commas)", "cover": "number", "premium": "number (no commas)" }
        ]
      }
    ]
  }
}

Important Rules:
1. Return ONLY the raw JSON string. Do not include markdown formatting like \`\`\`json.
2. Convert all dates to YYYY-MM-DD format.
3. For numbers (sum, premium, cover, deductible), remove any currency symbols and commas.
4. If a section or field is missing, return an empty string or empty array as appropriate, do not omit the keys.
5. If the Medical type is "Port", set isPort to true and extract the portDate.

Text from PDF:
${text}
`;

  try {
    const response = await fetch(`https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent?key=${apiKey}`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: JSON.stringify({
        contents: [{ parts: [{ text: prompt }] }],
        generationConfig: {
          temperature: 0.1,
          responseMimeType: "application/json"
        }
      })
    });

    const data = await response.json();
    if (!response.ok) {
       throw new Error(data.error?.message || 'Failed to call Gemini API');
    }

    let resultText = data.candidates[0].content.parts[0].text;
    res.status(200).json(JSON.parse(resultText));

  } catch (error) {
    console.error('Gemini API Error:', error);
    res.status(500).json({ error: 'Failed to process PDF text with Gemini' });
  }
}
